version: '2'
services:
    message-server:
        container_name: santa-hoods
        build:
            context: .
            dockerfile: Dockerfile
        image: santa-hoods:latest
        ports:
            - "8080:8080"
        networks:
            - spring-cloud-network

networks:
    spring-cloud-network:
        driver: bridge
